package com.greendao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.greendao.dao.Word;
import com.greendao.dao.Sentence;

import com.greendao.dao.WordDao;
import com.greendao.dao.SentenceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wordDaoConfig;
    private final DaoConfig sentenceDaoConfig;

    private final WordDao wordDao;
    private final SentenceDao sentenceDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wordDaoConfig = daoConfigMap.get(WordDao.class).clone();
        wordDaoConfig.initIdentityScope(type);

        sentenceDaoConfig = daoConfigMap.get(SentenceDao.class).clone();
        sentenceDaoConfig.initIdentityScope(type);

        wordDao = new WordDao(wordDaoConfig, this);
        sentenceDao = new SentenceDao(sentenceDaoConfig, this);

        registerDao(Word.class, wordDao);
        registerDao(Sentence.class, sentenceDao);
    }
    
    public void clear() {
        wordDaoConfig.getIdentityScope().clear();
        sentenceDaoConfig.getIdentityScope().clear();
    }

    public WordDao getWordDao() {
        return wordDao;
    }

    public SentenceDao getSentenceDao() {
        return sentenceDao;
    }

}
