package com.greendao.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SENTENCE".
 */
public class Sentence {

    private Long id;
    private String sentence;
    private String translation;
    private Long shanbay_id;

    public Sentence() {
    }

    public Sentence(Long id) {
        this.id = id;
    }

    public Sentence(Long id, String sentence, String translation, Long shanbay_id) {
        this.id = id;
        this.sentence = sentence;
        this.translation = translation;
        this.shanbay_id = shanbay_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSentence() {
        return sentence;
    }

    public void setSentence(String sentence) {
        this.sentence = sentence;
    }

    public String getTranslation() {
        return translation;
    }

    public void setTranslation(String translation) {
        this.translation = translation;
    }

    public Long getShanbay_id() {
        return shanbay_id;
    }

    public void setShanbay_id(Long shanbay_id) {
        this.shanbay_id = shanbay_id;
    }

}
