package com.greendao.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "WORD".
 */
public class Word {

    private Long id;
    private Long shanbay_id;
    private Long learning_id;
    private String word;
    private String pronounce;
    private String definition;
    private String audio;

    public Word() {
    }

    public Word(Long id) {
        this.id = id;
    }

    public Word(Long id, Long shanbay_id, Long learning_id, String word, String pronounce, String definition, String audio) {
        this.id = id;
        this.shanbay_id = shanbay_id;
        this.learning_id = learning_id;
        this.word = word;
        this.pronounce = pronounce;
        this.definition = definition;
        this.audio = audio;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getShanbay_id() {
        return shanbay_id;
    }

    public void setShanbay_id(Long shanbay_id) {
        this.shanbay_id = shanbay_id;
    }

    public Long getLearning_id() {
        return learning_id;
    }

    public void setLearning_id(Long learning_id) {
        this.learning_id = learning_id;
    }

    public String getWord() {
        return word;
    }

    public void setWord(String word) {
        this.word = word;
    }

    public String getPronounce() {
        return pronounce;
    }

    public void setPronounce(String pronounce) {
        this.pronounce = pronounce;
    }

    public String getDefinition() {
        return definition;
    }

    public void setDefinition(String definition) {
        this.definition = definition;
    }

    public String getAudio() {
        return audio;
    }

    public void setAudio(String audio) {
        this.audio = audio;
    }

}
